In [36]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch

In [5]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [7]:
df.shape

(569, 33)

In [9]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [17]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [19]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [23]:
scaler=StandardScaler()
X_train=scaler.fit_transform(x_train)
X_test=scaler.fit_transform(x_test)

In [25]:
X_train

array([[-0.34845962, -0.62498328, -0.40442369, ..., -0.84174005,
        -0.85688363, -1.10965173],
       [-0.06398697, -0.7875506 , -0.1159953 , ..., -1.22984568,
        -1.68991398, -0.89234827],
       [-1.00274673, -0.97566421, -0.97633599, ..., -0.32406453,
         0.15578876,  0.64833321],
       ...,
       [-0.70120571, -1.10107328, -0.68131495, ..., -0.68528969,
        -0.94273027, -0.17307384],
       [-0.29725454, -0.20695304, -0.2886403 , ..., -0.73210399,
         0.4530725 , -0.65494425],
       [-0.92593911, -0.9779866 , -0.94460886, ..., -1.21459328,
        -0.98883309, -0.91462188]])

In [27]:
y_train

69     B
442    B
426    B
360    B
75     M
      ..
188    B
129    M
540    B
402    B
144    B
Name: diagnosis, Length: 455, dtype: object

In [29]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [31]:
y_train

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,

Numpy to Pytorch conversion for building tensors

In [38]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [44]:
X_train_tensor

tensor([[-0.3485, -0.6250, -0.4044,  ..., -0.8417, -0.8569, -1.1097],
        [-0.0640, -0.7876, -0.1160,  ..., -1.2298, -1.6899, -0.8923],
        [-1.0027, -0.9757, -0.9763,  ..., -0.3241,  0.1558,  0.6483],
        ...,
        [-0.7012, -1.1011, -0.6813,  ..., -0.6853, -0.9427, -0.1731],
        [-0.2973, -0.2070, -0.2886,  ..., -0.7321,  0.4531, -0.6549],
        [-0.9259, -0.9780, -0.9446,  ..., -1.2146, -0.9888, -0.9146]],
       dtype=torch.float64)

In [40]:
X_train_tensor.shape

torch.Size([455, 30])

In [42]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [105]:
class mysimpleNN():
    def __init__(self,X):
        self.weight=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
    def forward(self,X):
        z=torch.matmul(X,self.weight)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):
        #clamp prediction to avoid log(0)
        epsilon=1e-7
        y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
        #calculate loss
        loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss
        

#Important Parameters

In [108]:
learning_rate=0.1
epochs=25

Training Pipeline

In [113]:
#creating Model
model=mysimpleNN(X_train_tensor)
for epoch in range(epochs):
    #forward pass
    y_pred=model.forward(X_train_tensor)
    #Loss  calculate
    loss=model.loss_function(y_pred,y_train_tensor)
    print(f'Epoch:{epoch+1},loss={loss.item()}')
    #backward pass
    loss.backward()

    #parameter update
    with torch.no_grad():
        model.weight-=learning_rate*model.weight.grad
        model.bias-=learning_rate*model.bias.grad
    
    #zero gradients
    model.weight.grad.zero_()
    model.bias.grad.zero_()

Epoch:1,loss=3.846847934000296
Epoch:2,loss=3.7319734838845657
Epoch:3,loss=3.6133348588113385
Epoch:4,loss=3.4880656460567607
Epoch:5,loss=3.357996266639917
Epoch:6,loss=3.2269987779942664
Epoch:7,loss=3.0955821446024765
Epoch:8,loss=2.959703216249296
Epoch:9,loss=2.815811931481132
Epoch:10,loss=2.6712047899216325
Epoch:11,loss=2.5277030956807516
Epoch:12,loss=2.3852277666675237
Epoch:13,loss=2.244228502578155
Epoch:14,loss=2.104412921899889
Epoch:15,loss=1.9637421620315259
Epoch:16,loss=1.8218317003141011
Epoch:17,loss=1.6842271852017665
Epoch:18,loss=1.553112763295537
Epoch:19,loss=1.4319280736071105
Epoch:20,loss=1.3245368005351505
Epoch:21,loss=1.2313765508468069
Epoch:22,loss=1.1520933301641403
Epoch:23,loss=1.0855131250204098
Epoch:24,loss=1.0299394221145965
Epoch:25,loss=0.9835793493975317


In [117]:
model.bias

tensor([-0.1529], dtype=torch.float64, requires_grad=True)

In [133]:
#model evaluvation
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.9).float()
    accuracy=(y_pred==y_train_tensor).float().mean()
    print(f'accuracy:{accuracy.item()}')

accuracy:0.6229034066200256
